"""Generate the served web assets from the PNG masters in frontend/media-masters (requires Pillow).

Masters stay outside frontend/public so Vite never copies ~21 MB of originals into dist/.
Everything this writes is committed, so the Docker build needs no image tooling.
"""

import base64
from io import BytesIO
from pathlib import Path

from PIL import Image

FRONTEND = Path(__file__).resolve().parents[1] / "frontend"
MASTERS = FRONTEND / "media-masters"
PUBLIC = FRONTEND / "public"

# The hero art is photographic, so lossy WebP at this quality is indistinguishable at display size.
# The logo keeps a higher quality because flat artwork shows ringing much sooner.
PHOTO_QUALITY = 76
LOGO_QUALITY = 88
PREVIEW_EDGE = 32


def encoded_webp(image: Image.Image, **options: object) -> str:
    buffer = BytesIO()
    image.save(buffer, "WEBP", **options)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def write_text(path: Path, text: str) -> None:
    """Writes LF endings on every platform so the generated files stay Prettier-clean."""
    path.write_text(text, encoding="utf-8", newline="\n")


declarations = []
mobile = []
for source in sorted((MASTERS / "media").glob("*.png")):
    with Image.open(source) as master:
        master = master.convert("RGB")
        for width, suffix in ((1280, ""), (640, "-640")):
            resized = master.copy()
            resized.thumbnail((width, width), Image.Resampling.LANCZOS)
            resized.save(PUBLIC / "media" / f"{source.stem}{suffix}.webp", "WEBP", quality=PHOTO_QUALITY, method=6)
        preview = master.copy()
        preview.thumbnail((PREVIEW_EDGE, PREVIEW_EDGE), Image.Resampling.LANCZOS)
        key = source.stem.removeprefix("tezfarmo-")
        declarations.extend(
            [
                f"  --media-{key}: url('/media/{source.stem}.webp');",
                f"  --preview-{key}: url('data:image/webp;base64,{encoded_webp(preview, quality=35)}');",
            ]
        )
        mobile.append(f"    --media-{key}: url('/media/{source.stem}-640.webp');")

# The logo renders at most 80 CSS px tall and its frame shows 71% of the master's height, so a 3x
# display needs about 340 px. 384 px keeps it crisp at a third of the bytes 512 px cost.
for name in ("light", "dark"):
    with Image.open(MASTERS / "brand" / f"tezfarmo-reference-{name}.png") as logo:
        logo.thumbnail((384, 384), Image.Resampling.LANCZOS)
        logo.save(PUBLIC / "brand" / f"tezfarmo-reference-{name}.webp", "WEBP", quality=LOGO_QUALITY, method=6)

# The favicon master carries full-resolution artwork plus C2PA provenance chunks (792 KB on every
# page load). Re-encode only the visible crop at tab size and drop the metadata.
FAVICON_CROP = (190, 210, 875, 605)
with Image.open(MASTERS / "favicon.png") as favicon:
    left, top, width, height = FAVICON_CROP
    cropped = favicon.convert("RGBA").crop((left, top, left + width, top + height))
    cropped.thumbnail((96, 96), Image.Resampling.LANCZOS)
    write_text(
        PUBLIC / "favicon.svg",
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {cropped.width} {cropped.height}">'
        f'<image href="data:image/webp;base64,{encoded_webp(cropped, quality=LOGO_QUALITY, method=6)}"'
        f' width="{cropped.width}" height="{cropped.height}"/></svg>\n',
    )

write_text(
    FRONTEND / "src/features/public/media-previews.css",
    "/* Generated by scripts/optimize_site_media.py; PNG masters live in frontend/media-masters. */\n"
    + ":root {\n"
    + "\n".join(declarations)
    + "\n}\n"
    + "@media (max-width: 640px) {\n  :root {\n"
    + "\n".join(mobile)
    + "\n  }\n}\n",
)
