"""p08 deliveries runs and courier sync

Revision ID: 581393db10d3
Revises: f78d0fa3dbff
Create Date: 2026-10-06 17:27:16.451808
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "581393db10d3"
down_revision = "f78d0fa3dbff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courier_sync_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=False),
        sa.Column("operation_type", sa.String(length=24), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("client_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_status", sa.String(length=16), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.CheckConstraint(
            "operation_type IN ('DELIVERY_ARRIVE','DELIVERY_CONFIRM','DELIVERY_FAIL','PAYMENT_RECORD')",
            name=op.f("ck_courier_sync_operations_operation_type"),
        ),
        sa.CheckConstraint(
            "result_status IN ('APPLIED','DUPLICATE','CONFLICT','REJECTED')",
            name=op.f("ck_courier_sync_operations_result_status"),
        ),
        sa.ForeignKeyConstraint(["courier_id"], ["users.id"], name=op.f("fk_courier_sync_operations_courier_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_sync_operations")),
    )
    op.create_index("ix_courier_sync_received", "courier_sync_operations", ["received_at"], unique=False)
    op.create_table(
        "delivery_runs",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="DRAFT", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','STARTED','FINISHED','CANCELLED')", name=op.f("ck_delivery_runs_status")
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_delivery_runs_company_id_companies")),
        sa.ForeignKeyConstraint(["courier_id"], ["users.id"], name=op.f("fk_delivery_runs_courier_id_users")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_delivery_runs_created_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_runs")),
    )
    op.create_index("ix_delivery_runs_company_date", "delivery_runs", ["company_id", "run_date"], unique=False)
    op.create_index("ix_delivery_runs_courier_date", "delivery_runs", ["courier_id", "run_date"], unique=False)
    op.create_table(
        "deliveries",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_no", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PLANNED", nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("stop_sequence", sa.SmallInteger(), nullable=True),
        sa.Column("courier_id", sa.Uuid(), nullable=True),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=True),
        sa.Column("code_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("code_attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("code_locked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("confirmation_method", sa.String(length=16), nullable=True),
        sa.Column("manual_reason", sa.Text(), nullable=True),
        sa.Column("failure_reason_code", sa.String(length=24), nullable=True),
        sa.Column("failure_note", sa.Text(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "confirmation_method <> 'MANUAL_OVERRIDE' OR (manual_reason IS NOT NULL AND length(btrim(manual_reason)) >= 10)",
            name=op.f("ck_deliveries_manual_reason"),
        ),
        sa.CheckConstraint(
            "confirmation_method IS NULL OR confirmation_method IN ('CODE','MANUAL_OVERRIDE')",
            name=op.f("ck_deliveries_confirmation_method"),
        ),
        sa.CheckConstraint(
            "failure_reason_code <> 'OTHER' OR (failure_note IS NOT NULL AND length(btrim(failure_note)) >= 1)",
            name=op.f("ck_deliveries_failure_note"),
        ),
        sa.CheckConstraint(
            "failure_reason_code IS NULL OR failure_reason_code IN ('STORE_CLOSED','REFUSED','ADDRESS_NOT_FOUND','NO_CONTACT','VEHICLE_ISSUE','OTHER')",
            name=op.f("ck_deliveries_failure_reason_code"),
        ),
        sa.CheckConstraint(
            "status IN ('PLANNED','ASSIGNED','IN_TRANSIT','ARRIVED','DELIVERED','FAILED','CANCELLED')",
            name=op.f("ck_deliveries_status"),
        ),
        sa.CheckConstraint(
            "(latitude IS NULL) = (longitude IS NULL)", name=op.f("ck_deliveries_coordinates_both_or_none")
        ),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_deliveries_attempt_no_positive")),
        sa.CheckConstraint("code_attempts >= 0", name=op.f("ck_deliveries_code_attempts_nonnegative")),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90", name=op.f("ck_deliveries_latitude_range")
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name=op.f("ck_deliveries_longitude_range")
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_deliveries_company_id_companies")),
        sa.ForeignKeyConstraint(["courier_id"], ["users.id"], name=op.f("fk_deliveries_courier_id_users")),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_deliveries_order_id_orders")),
        sa.ForeignKeyConstraint(["run_id"], ["delivery_runs.id"], name=op.f("fk_deliveries_run_id_delivery_runs")),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_deliveries_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
    )
    op.create_index("ix_deliveries_company_status", "deliveries", ["company_id", "status"], unique=False)
    op.create_index("ix_deliveries_courier_status", "deliveries", ["courier_id", "status"], unique=False)
    op.create_index("uq_deliveries_order_attempt", "deliveries", ["order_id", "attempt_no"], unique=True)
    op.create_index(
        "uq_deliveries_order_open",
        "deliveries",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PLANNED','ASSIGNED','IN_TRANSIT','ARRIVED')"),
    )
    op.create_index(
        "uq_deliveries_run_stop",
        "deliveries",
        ["run_id", "stop_sequence"],
        unique=True,
        postgresql_where=sa.text("run_id IS NOT NULL AND stop_sequence IS NOT NULL"),
    )
    op.create_table(
        "delivery_status_history",
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), server_default="ONLINE", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("actor_type IN ('USER','SYSTEM')", name=op.f("ck_delivery_status_history_actor_type")),
        sa.CheckConstraint("source IN ('ONLINE','OFFLINE_SYNC')", name=op.f("ck_delivery_status_history_source")),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_delivery_status_history_actor_id_users")),
        sa.ForeignKeyConstraint(
            ["delivery_id"], ["deliveries.id"], name=op.f("fk_delivery_status_history_delivery_id_deliveries")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_status_history")),
    )
    op.create_index(
        "ix_delivery_history_created", "delivery_status_history", ["delivery_id", "created_at"], unique=False
    )
    # The history is the audit trail for a handover; it is appended to and never edited.
    op.execute(
        "CREATE TRIGGER delivery_history_immutable BEFORE UPDATE OR DELETE ON delivery_status_history "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    # DEL-023: a replayed queue must get the recorded answer, not a second attempt at the work.
    op.execute("""
        CREATE FUNCTION protect_courier_sync() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' AND OLD.received_at < now() - interval '30 days' THEN
            RETURN OLD;
          END IF;
          RAISE EXCEPTION 'courier sync log is immutable during retention';
        END $$
    """)
    op.execute(
        "CREATE TRIGGER courier_sync_immutable BEFORE UPDATE OR DELETE ON courier_sync_operations "
        "FOR EACH ROW EXECUTE FUNCTION protect_courier_sync()"
    )
    op.execute("""
        CREATE FUNCTION protect_delivery() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM orders o WHERE o.id = NEW.order_id
              AND o.company_id = NEW.company_id AND o.store_id = NEW.store_id)
          THEN RAISE EXCEPTION 'delivery order ownership mismatch'; END IF;
          IF NEW.run_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM delivery_runs r
              WHERE r.id = NEW.run_id AND r.company_id = NEW.company_id)
          THEN RAISE EXCEPTION 'delivery run ownership mismatch'; END IF;
          IF TG_OP = 'UPDATE' THEN
            IF ROW(NEW.id, NEW.company_id, NEW.store_id, NEW.order_id, NEW.attempt_no, NEW.created_at)
              IS DISTINCT FROM ROW(OLD.id, OLD.company_id, OLD.store_id, OLD.order_id, OLD.attempt_no, OLD.created_at)
            THEN RAISE EXCEPTION 'delivery identity is immutable'; END IF;
            -- A finished delivery never moves again; a reattempt is a new row (DEL-001). The rest of
            -- the row stays editable so a run can still be tidied up around a stop that is done.
            IF OLD.status IN ('DELIVERED','FAILED','CANCELLED') AND NEW.status IS DISTINCT FROM OLD.status
            THEN RAISE EXCEPTION 'delivery is already final'; END IF;
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER delivery_protection BEFORE INSERT OR UPDATE ON deliveries "
        "FOR EACH ROW EXECUTE FUNCTION protect_delivery()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS delivery_protection ON deliveries")
    op.execute("DROP FUNCTION IF EXISTS protect_delivery()")
    op.execute("DROP TRIGGER IF EXISTS courier_sync_immutable ON courier_sync_operations")
    op.execute("DROP FUNCTION IF EXISTS protect_courier_sync()")
    op.execute("DROP TRIGGER IF EXISTS delivery_history_immutable ON delivery_status_history")
    op.drop_index("ix_delivery_history_created", table_name="delivery_status_history")
    op.drop_table("delivery_status_history")
    op.drop_index(
        "uq_deliveries_run_stop",
        table_name="deliveries",
        postgresql_where=sa.text("run_id IS NOT NULL AND stop_sequence IS NOT NULL"),
    )
    op.drop_index(
        "uq_deliveries_order_open",
        table_name="deliveries",
        postgresql_where=sa.text("status IN ('PLANNED','ASSIGNED','IN_TRANSIT','ARRIVED')"),
    )
    op.drop_index("uq_deliveries_order_attempt", table_name="deliveries")
    op.drop_index("ix_deliveries_courier_status", table_name="deliveries")
    op.drop_index("ix_deliveries_company_status", table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index("ix_delivery_runs_courier_date", table_name="delivery_runs")
    op.drop_index("ix_delivery_runs_company_date", table_name="delivery_runs")
    op.drop_table("delivery_runs")
    op.drop_index("ix_courier_sync_received", table_name="courier_sync_operations")
    op.drop_table("courier_sync_operations")
    # ### end Alembic commands ###
