"""identity users organizations memberships

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 16:38:35.894464
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=2), server_default="tg", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("is_superadmin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("language IN ('tg','ru','en')", name=op.f("ck_users_language")),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_users_phone_e164")),
        sa.CheckConstraint("status IN ('ACTIVE','BLOCKED')", name=op.f("ck_users_status")),
        sa.CheckConstraint(
            "email_verified_at IS NULL OR email IS NOT NULL", name=op.f("ck_users_email_verified_requires_email")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "oauth_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("provider IN ('google')", name=op.f("ck_oauth_identities_provider")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_oauth_identities_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_identities")),
    )
    op.create_index(op.f("ix_oauth_identities_user_id"), "oauth_identities", ["user_id"], unique=False)
    op.create_index("uq_oauth_identities_provider_subject", "oauth_identities", ["provider", "subject"], unique=True)
    op.create_index("uq_oauth_identities_provider_user", "oauth_identities", ["provider", "user_id"], unique=True)
    op.create_table(
        "organizations",
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED','BLOCKED')", name=op.f("ck_organizations_status")),
        sa.CheckConstraint("type IN ('COMPANY','STORE')", name=op.f("ck_organizations_type")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_organizations_created_by_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('OWNER','MANAGER','OPERATOR','WAREHOUSE','COURIER','SELLER')", name=op.f("ck_memberships_role")
        ),
        sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED','REVOKED')", name=op.f("ck_memberships_status")),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.id"], name=op.f("fk_memberships_invited_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
    )
    op.create_index(op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_index(
        "uq_memberships_single_owner",
        "memberships",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("role = 'OWNER' AND status = 'ACTIVE'"),
    )
    op.create_index(
        "uq_memberships_user_org_open",
        "memberships",
        ["user_id", "organization_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'REVOKED'"),
    )
    # ### end Alembic commands ###

    # P01 §2.5: membership role must belong to the organization type (checked in service and here).
    op.execute(
        """
        CREATE FUNCTION check_membership_role() RETURNS trigger AS $$
        DECLARE org_type varchar;
        BEGIN
          SELECT type INTO org_type FROM organizations WHERE id = NEW.organization_id;
          IF (org_type = 'COMPANY' AND NEW.role NOT IN ('OWNER','MANAGER','OPERATOR','WAREHOUSE','COURIER'))
             OR (org_type = 'STORE' AND NEW.role NOT IN ('OWNER','SELLER')) THEN
            RAISE EXCEPTION 'role % is not allowed for % organizations', NEW.role, org_type USING ERRCODE = '23514';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER memberships_role_matches_org BEFORE INSERT OR UPDATE OF role, organization_id "
        "ON memberships FOR EACH ROW EXECUTE FUNCTION check_membership_role();"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS memberships_role_matches_org ON memberships;")
    op.execute("DROP FUNCTION IF EXISTS check_membership_role();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_memberships_user_org_open", table_name="memberships", postgresql_where=sa.text("status <> 'REVOKED'")
    )
    op.drop_index(
        "uq_memberships_single_owner",
        table_name="memberships",
        postgresql_where=sa.text("role = 'OWNER' AND status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_table("organizations")
    op.drop_index("uq_oauth_identities_provider_user", table_name="oauth_identities")
    op.drop_index("uq_oauth_identities_provider_subject", table_name="oauth_identities")
    op.drop_index(op.f("ix_oauth_identities_user_id"), table_name="oauth_identities")
    op.drop_table("oauth_identities")
    op.drop_index("uq_users_email_lower", table_name="users", postgresql_where=sa.text("email IS NOT NULL"))
    op.drop_table("users")
    # ### end Alembic commands ###
