"""organization profiles files and verification

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 20:04:14.960297
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tax_identifier", sa.String(length=32), nullable=False),
        sa.Column("public_code", sa.String(length=8), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("verification_status", sa.String(length=16), server_default="NOT_SUBMITTED", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_companies_phone_e164")),
        sa.CheckConstraint("public_code ~ '^[A-HJ-NP-Z2-9]{8}$'", name=op.f("ck_companies_public_code_format")),
        sa.CheckConstraint("tax_identifier ~ '^[0-9]{9,12}$'", name=op.f("ck_companies_tax_identifier_format")),
        sa.CheckConstraint(
            "verification_status IN ('NOT_SUBMITTED','PENDING','APPROVED','REJECTED')",
            name=op.f("ck_companies_verification_status"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["organizations.id"], name=op.f("fk_companies_id_organizations"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("public_code", name=op.f("uq_companies_public_code")),
        sa.UniqueConstraint("tax_identifier", name=op.f("uq_companies_tax_identifier")),
    )
    op.create_table(
        "stored_files",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IN ('VERIFICATION','IMPORT','EXPORT','PRODUCT_IMAGE')", name=op.f("ck_stored_files_category")
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_stored_files_size_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_stored_files_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_stored_files_uploaded_by_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_stored_files_storage_key")),
    )
    op.create_index(op.f("ix_stored_files_organization_id"), "stored_files", ["organization_id"], unique=False)
    op.create_table(
        "stores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tax_identifier", sa.String(length=32), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("verification_status", sa.String(length=16), server_default="NOT_SUBMITTED", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_stores_phone_e164")),
        sa.CheckConstraint(
            "tax_identifier IS NULL OR tax_identifier ~ '^[0-9]{9,12}$'", name=op.f("ck_stores_tax_identifier_format")
        ),
        sa.CheckConstraint(
            "verification_status IN ('NOT_SUBMITTED','PENDING','APPROVED','REJECTED')",
            name=op.f("ck_stores_verification_status"),
        ),
        sa.CheckConstraint("(latitude IS NULL) = (longitude IS NULL)", name=op.f("ck_stores_coordinates_both_or_none")),
        sa.CheckConstraint("latitude IS NULL OR latitude BETWEEN -90 AND 90", name=op.f("ck_stores_latitude_range")),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name=op.f("ck_stores_longitude_range")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["organizations.id"], name=op.f("fk_stores_id_organizations"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
    )
    op.create_index(
        "uq_stores_tax_identifier",
        "stores",
        ["tax_identifier"],
        unique=True,
        postgresql_where=sa.text("tax_identifier IS NOT NULL"),
    )
    op.create_table(
        "verification_requests",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("review_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("legal_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status <> 'REJECTED' OR rejection_reason IS NOT NULL",
            name=op.f("ck_verification_requests_rejection_reason_required"),
        ),
        sa.CheckConstraint(
            "status IN ('SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED')", name=op.f("ck_verification_requests_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_verification_requests_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_verification_requests_reviewer_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_verification_requests_submitted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_requests")),
    )
    op.create_index(
        op.f("ix_verification_requests_organization_id"), "verification_requests", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_verification_requests_open",
        "verification_requests",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('SUBMITTED','UNDER_REVIEW')"),
    )
    op.create_table(
        "verification_documents",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("doc_type", sa.String(length=32), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "doc_type IN ('REGISTRATION_CERTIFICATE','TAX_CERTIFICATE','OTHER')",
            name=op.f("ck_verification_documents_doc_type"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_files.id"],
            name=op.f("fk_verification_documents_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["verification_requests.id"],
            name=op.f("fk_verification_documents_request_id_verification_requests"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_documents")),
    )
    op.create_index(
        op.f("ix_verification_documents_request_id"), "verification_documents", ["request_id"], unique=False
    )
    # ### end Alembic commands ###

    # VER-005: verification requests, their documents and the stored files are never deleted.
    for table in ("verification_requests", "verification_documents", "stored_files"):
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_mutation();"
        )


def downgrade() -> None:
    for table in ("verification_requests", "verification_documents", "stored_files"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete ON {table};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_documents_request_id"), table_name="verification_documents")
    op.drop_table("verification_documents")
    op.drop_index(
        "uq_verification_requests_open",
        table_name="verification_requests",
        postgresql_where=sa.text("status IN ('SUBMITTED','UNDER_REVIEW')"),
    )
    op.drop_index(op.f("ix_verification_requests_organization_id"), table_name="verification_requests")
    op.drop_table("verification_requests")
    op.drop_index(
        "uq_stores_tax_identifier", table_name="stores", postgresql_where=sa.text("tax_identifier IS NOT NULL")
    )
    op.drop_table("stores")
    op.drop_index(op.f("ix_stored_files_organization_id"), table_name="stored_files")
    op.drop_table("stored_files")
    op.drop_table("companies")
    # ### end Alembic commands ###
