"""catalog pricing and imports

Revision ID: 20261005_0019
Revises: 0018
Create Date: 2026-10-05 15:39:15.040502
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "20261005_0019"
down_revision = "0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_categories_company_id_companies")),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], name=op.f("fk_categories_parent_id_categories")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(op.f("ix_categories_company_id"), "categories", ["company_id"], unique=False)
    op.create_index(
        "uq_categories_company_parent_name",
        "categories",
        ["company_id", "parent_id", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "imports",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="UPLOADED", nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("total_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('PRODUCTS','PRICES','STOCK')", name=op.f("ck_imports_kind")),
        sa.CheckConstraint(
            "status IN ('UPLOADED','VALIDATED','CONFIRMED','COMPLETED','FAILED','CANCELLED')",
            name=op.f("ck_imports_status"),
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_imports_company_id_companies")),
        sa.ForeignKeyConstraint(["confirmed_by"], ["users.id"], name=op.f("fk_imports_confirmed_by_users")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_imports_created_by_users")),
        sa.ForeignKeyConstraint(["file_id"], ["stored_files.id"], name=op.f("fk_imports_file_id_stored_files")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
    )
    op.create_index(op.f("ix_imports_company_id"), "imports", ["company_id"], unique=False)
    op.create_table(
        "price_lists",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("NOT is_default OR is_active", name=op.f("ck_price_lists_default_active")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_price_lists_company_id_companies")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_lists")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_price_lists_company_id_code")),
    )
    op.create_index(op.f("ix_price_lists_company_id"), "price_lists", ["company_id"], unique=False)
    op.create_index(
        "uq_price_lists_default", "price_lists", ["company_id"], unique=True, postgresql_where=sa.text("is_default")
    )
    op.create_table(
        "import_errors",
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.Column("message_key", sa.String(length=128), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], name=op.f("fk_import_errors_import_id_imports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_errors")),
    )
    op.create_index(op.f("ix_import_errors_import_id"), "import_errors", ["import_id"], unique=False)
    op.create_table(
        "import_rows",
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("action IN ('CREATE','UPDATE','SKIP')", name=op.f("ck_import_rows_action")),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], name=op.f("fk_import_rows_import_id_imports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_rows")),
        sa.UniqueConstraint("import_id", "row_number", name=op.f("uq_import_rows_import_id_row_number")),
    )
    op.create_index(op.f("ix_import_rows_import_id"), "import_rows", ["import_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("barcode", sa.String(length=32), nullable=True),
        sa.Column("base_unit", sa.String(length=8), nullable=False),
        sa.Column("image_file_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("base_unit IN ('PCS','KG','G','L','ML','M','PACK')", name=op.f("ck_products_base_unit")),
        sa.CheckConstraint("sku ~ '^[A-Za-z0-9._-]+$'", name=op.f("ck_products_sku_format")),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], name=op.f("fk_products_category_id_categories")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_products_company_id_companies")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_products_created_by_users")),
        sa.ForeignKeyConstraint(
            ["image_file_id"], ["stored_files.id"], name=op.f("fk_products_image_file_id_stored_files")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("company_id", "sku", name="uq_products_company_sku"),
    )
    op.create_index(op.f("ix_products_company_id"), "products", ["company_id"], unique=False)
    op.create_index(
        "ix_products_name_trgm",
        "products",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_products_sku_trgm",
        "products",
        ["sku"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sku": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_products_company_barcode",
        "products",
        ["company_id", "barcode"],
        unique=True,
        postgresql_where=sa.text("barcode IS NOT NULL"),
    )
    op.create_table(
        "product_units",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coefficient", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("is_base", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("allow_fraction", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("min_order_qty", sa.Numeric(precision=14, scale=3), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("NOT is_base OR coefficient = 1", name=op.f("ck_product_units_base_coefficient")),
        sa.CheckConstraint("NOT is_base OR is_active", name=op.f("ck_product_units_base_active")),
        sa.CheckConstraint("coefficient > 0", name=op.f("ck_product_units_coefficient_positive")),
        sa.CheckConstraint("min_order_qty > 0", name=op.f("ck_product_units_quantity_positive")),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_product_units_product_id_products")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_units")),
        sa.UniqueConstraint("product_id", "code", name=op.f("uq_product_units_product_id_code")),
    )
    op.create_index(op.f("ix_product_units_product_id"), "product_units", ["product_id"], unique=False)
    op.create_index(
        "uq_product_units_base", "product_units", ["product_id"], unique=True, postgresql_where=sa.text("is_base")
    )
    op.create_table(
        "prices",
        sa.Column("price_list_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("price_list_id"), "="),
            (sa.column("product_unit_id"), "="),
            (sa.text("tstzrange(valid_from, valid_to, '[)')"), "&&"),
            using="gist",
            name="price_overlap",
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_prices_positive")),
        sa.CheckConstraint("valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_prices_valid_period")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_prices_created_by_users")),
        sa.ForeignKeyConstraint(
            ["price_list_id"], ["price_lists.id"], name=op.f("fk_prices_price_list_id_price_lists")
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"], ["product_units.id"], name=op.f("fk_prices_product_unit_id_product_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prices")),
    )
    op.create_index(op.f("ix_prices_price_list_id"), "prices", ["price_list_id"], unique=False)
    op.create_index(op.f("ix_prices_product_unit_id"), "prices", ["product_unit_id"], unique=False)
    op.execute("""
    CREATE FUNCTION p04_category_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE parent categories; BEGIN
      IF NEW.parent_id IS NOT NULL THEN
        SELECT * INTO parent FROM categories WHERE id = NEW.parent_id;
        IF parent.company_id <> NEW.company_id OR parent.parent_id IS NOT NULL
           OR NEW.parent_id = NEW.id OR NOT parent.is_active
           OR EXISTS (SELECT 1 FROM categories WHERE parent_id = NEW.id) THEN
          RAISE EXCEPTION 'category_depth_or_tenant' USING ERRCODE = '23514';
        END IF;
      END IF;
      IF NOT NEW.is_active AND (EXISTS(SELECT 1 FROM products WHERE category_id=NEW.id)
        OR EXISTS(SELECT 1 FROM categories WHERE parent_id=NEW.id AND is_active)) THEN
        RAISE EXCEPTION 'category_not_empty' USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER category_guard BEFORE INSERT OR UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION p04_category_guard()"
    )
    op.execute("""
    CREATE FUNCTION p04_product_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF NEW.category_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM categories WHERE id=NEW.category_id AND company_id=NEW.company_id
      ) THEN RAISE EXCEPTION 'category_tenant' USING ERRCODE = '23514'; END IF;
      IF NEW.image_file_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM stored_files WHERE id=NEW.image_file_id AND organization_id=NEW.company_id
          AND category='PRODUCT_IMAGE'
      ) THEN RAISE EXCEPTION 'image_tenant' USING ERRCODE = '23514'; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER product_guard BEFORE INSERT OR UPDATE ON products FOR EACH ROW EXECUTE FUNCTION p04_product_guard()"
    )
    op.execute("""
    CREATE FUNCTION p04_unit_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF NEW.code <> OLD.code OR NEW.coefficient <> OLD.coefficient OR NEW.product_id <> OLD.product_id
         OR NEW.is_base <> OLD.is_base THEN
        RAISE EXCEPTION 'unit_immutable' USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER unit_guard BEFORE UPDATE ON product_units FOR EACH ROW EXECUTE FUNCTION p04_unit_guard()"
    )
    op.execute("""
    CREATE FUNCTION p04_price_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF TG_OP = 'DELETE' THEN
        IF OLD.valid_from <= now() THEN RAISE EXCEPTION 'price_immutable' USING ERRCODE = '23514'; END IF;
        RETURN OLD;
      END IF;
      IF (to_jsonb(NEW) - 'valid_to') IS DISTINCT FROM (to_jsonb(OLD) - 'valid_to') THEN
        RAISE EXCEPTION 'price_immutable' USING ERRCODE = '23514';
      END IF;
      IF OLD.valid_to IS NOT NULL AND NEW.valid_to IS DISTINCT FROM OLD.valid_to THEN
        -- PRC-002 explicitly restores an interval after its future successor was deleted.
        IF NEW.valid_to IS NOT NULL OR OLD.valid_to <= now() OR EXISTS (
          SELECT 1 FROM prices WHERE price_list_id=OLD.price_list_id
            AND product_unit_id=OLD.product_unit_id AND valid_from=OLD.valid_to
        ) THEN RAISE EXCEPTION 'price_immutable' USING ERRCODE = '23514'; END IF;
      END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER price_guard BEFORE UPDATE OR DELETE ON prices FOR EACH ROW EXECUTE FUNCTION p04_price_guard()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for function in ("p04_category_guard", "p04_product_guard", "p04_unit_guard", "p04_price_guard"):
        op.execute(f"DROP FUNCTION IF EXISTS {function}() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prices_product_unit_id"), table_name="prices")
    op.drop_index(op.f("ix_prices_price_list_id"), table_name="prices")
    op.drop_table("prices")
    op.drop_index("uq_product_units_base", table_name="product_units", postgresql_where=sa.text("is_base"))
    op.drop_index(op.f("ix_product_units_product_id"), table_name="product_units")
    op.drop_table("product_units")
    op.drop_index("uq_products_company_barcode", table_name="products", postgresql_where=sa.text("barcode IS NOT NULL"))
    op.drop_index(
        "ix_products_sku_trgm", table_name="products", postgresql_using="gin", postgresql_ops={"sku": "gin_trgm_ops"}
    )
    op.drop_index(
        "ix_products_name_trgm", table_name="products", postgresql_using="gin", postgresql_ops={"name": "gin_trgm_ops"}
    )
    op.drop_index(op.f("ix_products_company_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_import_rows_import_id"), table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index(op.f("ix_import_errors_import_id"), table_name="import_errors")
    op.drop_table("import_errors")
    op.drop_index("uq_price_lists_default", table_name="price_lists", postgresql_where=sa.text("is_default"))
    op.drop_index(op.f("ix_price_lists_company_id"), table_name="price_lists")
    op.drop_table("price_lists")
    op.drop_index(op.f("ix_imports_company_id"), table_name="imports")
    op.drop_table("imports")
    op.drop_index("uq_categories_company_parent_name", table_name="categories", postgresql_nulls_not_distinct=True)
    op.drop_index(op.f("ix_categories_company_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
