"""P05 inventory stock ledger and reservations

Revision ID: 20261005_0020
Revises: 20261005_0019
Create Date: 2026-10-05 17:46:54.697203
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20261005_0020"
down_revision = "20261005_0019"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_movements",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("reserved_delta", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("quantity_after", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("reserved_after", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('MANUAL','IMPORT','ORDER','RETURN')", name=op.f("ck_stock_movements_source_type")
        ),
        sa.CheckConstraint(
            "type IN ('RECEIPT','ADJUSTMENT','WRITE_OFF','RESERVE','RELEASE','SHIP','RETURN_IN')",
            name=op.f("ck_stock_movements_type"),
        ),
        sa.CheckConstraint(
            "type NOT IN ('ADJUSTMENT','WRITE_OFF') OR (reason IS NOT NULL AND length(btrim(reason)) >= 5)",
            name=op.f("ck_stock_movements_reason"),
        ),
        sa.CheckConstraint(
            "quantity_after >= 0 AND reserved_after >= 0 AND reserved_after <= quantity_after",
            name=op.f("ck_stock_movements_balances"),
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_stock_movements_company_id_companies")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_stock_movements_created_by_users")),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_stock_movements_product_id_products")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index("ix_stock_movements_company_created", "stock_movements", ["company_id", "created_at"], unique=False)
    op.create_index("ix_stock_movements_product_created", "stock_movements", ["product_id", "created_at"], unique=False)
    op.create_index("ix_stock_movements_source", "stock_movements", ["source_type", "source_id"], unique=False)
    op.create_table(
        "stock_reservations",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("source_type = 'ORDER'", name=op.f("ck_stock_reservations_source_type")),
        sa.CheckConstraint("status IN ('ACTIVE','RELEASED','SHIPPED')", name=op.f("ck_stock_reservations_status")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_reservations_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_stock_reservations_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_stock_reservations_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_reservations")),
    )
    op.create_index(
        "ix_stock_reservations_company_source",
        "stock_reservations",
        ["company_id", "source_type", "source_id"],
        unique=False,
    )
    op.create_index(op.f("ix_stock_reservations_product_id"), "stock_reservations", ["product_id"], unique=False)
    op.create_index(
        "uq_stock_reservations_active_source",
        "stock_reservations",
        ["source_type", "source_id", "product_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "stocks",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), server_default="0", nullable=False),
        sa.Column("reserved_quantity", sa.Numeric(precision=14, scale=3), server_default="0", nullable=False),
        sa.Column("low_stock_threshold", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("last_movement_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "low_stock_threshold IS NULL OR low_stock_threshold >= 0", name=op.f("ck_stocks_threshold_nonnegative")
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_stocks_quantity_nonnegative")),
        sa.CheckConstraint("reserved_quantity <= quantity", name=op.f("ck_stocks_reserved_le_quantity")),
        sa.CheckConstraint("reserved_quantity >= 0", name=op.f("ck_stocks_reserved_nonnegative")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_stocks_company_id_companies")),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_stocks_product_id_products")),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_stocks")),
    )
    op.create_index(op.f("ix_stocks_company_id"), "stocks", ["company_id"], unique=False)
    op.execute("INSERT INTO stocks (product_id, company_id) SELECT id, company_id FROM products ON CONFLICT DO NOTHING")
    op.execute(
        "CREATE TRIGGER stock_movements_immutable BEFORE UPDATE OR DELETE ON stock_movements FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute("""
        CREATE FUNCTION p05_company_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM products WHERE id = NEW.product_id AND company_id = NEW.company_id) THEN
                RAISE EXCEPTION 'stock product belongs to another company' USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END $$
    """)
    for table in ("stocks", "stock_movements", "stock_reservations"):
        op.execute(
            f"CREATE TRIGGER stock_company_guard BEFORE INSERT OR UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION p05_company_guard()"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_company_id"), table_name="stocks")
    op.drop_table("stocks")
    op.drop_index(
        "uq_stock_reservations_active_source",
        table_name="stock_reservations",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_stock_reservations_product_id"), table_name="stock_reservations")
    op.drop_index("ix_stock_reservations_company_source", table_name="stock_reservations")
    op.drop_table("stock_reservations")
    op.drop_index("ix_stock_movements_source", table_name="stock_movements")
    op.drop_index("ix_stock_movements_product_created", table_name="stock_movements")
    op.drop_index("ix_stock_movements_company_created", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.execute("DROP FUNCTION p05_company_guard()")
    # ### end Alembic commands ###
