"""P10 returns, disputes and their append-only history.

Revision ID: 20261008_0025
Revises: 20261008_0024
Create Date: 2026-10-08 17:05:49.526650
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20261008_0025"
down_revision = "20261008_0024"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disputes",
        sa.Column("dispute_number", sa.String(length=20), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column("resolution_type", sa.String(length=24), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("pending_adjustment_id", sa.Uuid(), nullable=True),
        sa.Column("adjustment_id", sa.Uuid(), nullable=True),
        sa.Column("return_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status IN ('RESOLVED','REJECTED','WITHDRAWN')) = (resolved_at IS NOT NULL)",
            name=op.f("ck_disputes_resolved_at"),
        ),
        sa.CheckConstraint(
            "(target_type = 'ORDER' AND order_id IS NOT NULL AND payment_id IS NULL) OR (target_type = 'PAYMENT' AND payment_id IS NOT NULL AND order_id IS NULL)",
            name=op.f("ck_disputes_target_reference"),
        ),
        sa.CheckConstraint(
            "adjustment_id IS NULL OR resolution_type = 'ADJUSTMENT_CREDIT'",
            name=op.f("ck_disputes_adjustment_needs_resolution"),
        ),
        sa.CheckConstraint(
            "resolution_type IS NULL OR resolution_type IN ('NO_ACTION','ADJUSTMENT_CREDIT','CONVERTED_TO_RETURN')",
            name=op.f("ck_disputes_resolution"),
        ),
        sa.CheckConstraint(
            "return_id IS NULL OR resolution_type = 'CONVERTED_TO_RETURN'",
            name=op.f("ck_disputes_return_needs_resolution"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','UNDER_REVIEW','RESOLVED','REJECTED','WITHDRAWN')", name=op.f("ck_disputes_status")
        ),
        sa.CheckConstraint("target_type IN ('ORDER','PAYMENT')", name=op.f("ck_disputes_target_type")),
        sa.CheckConstraint(
            "type IN ('QUANTITY','PRICE','DAMAGED','DELIVERY','PAYMENT','OTHER')", name=op.f("ck_disputes_type")
        ),
        sa.CheckConstraint("length(trim(description)) >= 10", name=op.f("ck_disputes_description_length")),
        sa.ForeignKeyConstraint(
            ["adjustment_id"], ["adjustments.id"], name=op.f("fk_disputes_adjustment_id_adjustments")
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_disputes_company_id_companies")),
        sa.ForeignKeyConstraint(["opened_by"], ["users.id"], name=op.f("fk_disputes_opened_by_users")),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_disputes_order_id_orders")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_disputes_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], name=op.f("fk_disputes_payment_id_payments")),
        sa.ForeignKeyConstraint(
            ["pending_adjustment_id"], ["adjustments.id"], name=op.f("fk_disputes_pending_adjustment_id_adjustments")
        ),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], name=op.f("fk_disputes_resolved_by_users")),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_disputes_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disputes")),
        sa.UniqueConstraint("company_id", "dispute_number", name=op.f("uq_disputes_company_id_dispute_number")),
    )
    op.create_index(
        "ix_disputes_company_status_created", "disputes", ["company_id", "status", "created_at"], unique=False
    )
    op.create_index("ix_disputes_partnership_created", "disputes", ["partnership_id", "created_at"], unique=False)
    op.create_index("ix_disputes_store_created", "disputes", ["store_id", "created_at"], unique=False)
    op.create_index(
        "uq_disputes_open_order",
        "disputes",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('OPEN','UNDER_REVIEW')"),
    )
    op.create_table(
        "dispute_messages",
        sa.Column("dispute_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("author_side", sa.String(length=8), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(author_side = 'SYSTEM') = (author_id IS NULL)", name=op.f("ck_dispute_messages_system_has_no_author")
        ),
        sa.CheckConstraint("author_side IN ('COMPANY','STORE','SYSTEM')", name=op.f("ck_dispute_messages_author_side")),
        sa.CheckConstraint(
            "length(trim(body)) > 0 AND length(body) <= 2000", name=op.f("ck_dispute_messages_body_length")
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_dispute_messages_author_id_users")),
        sa.ForeignKeyConstraint(["dispute_id"], ["disputes.id"], name=op.f("fk_dispute_messages_dispute_id_disputes")),
        sa.ForeignKeyConstraint(
            ["file_id"], ["stored_files.id"], name=op.f("fk_dispute_messages_file_id_stored_files")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispute_messages")),
    )
    op.create_index("ix_dispute_messages_created", "dispute_messages", ["dispute_id", "created_at"], unique=False)
    op.create_table(
        "returns",
        sa.Column("return_number", sa.String(length=20), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="REQUESTED", nullable=False),
        sa.Column("reason_code", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), server_default="STORE_REQUEST", nullable=False),
        sa.Column("dispute_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("received_by", sa.Uuid(), nullable=True),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("total_credit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("credit_note_id", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("(source = 'DISPUTE') = (dispute_id IS NOT NULL)", name=op.f("ck_returns_dispute_source")),
        sa.CheckConstraint("(status = 'COMPLETED') = (completed_at IS NOT NULL)", name=op.f("ck_returns_completed_at")),
        sa.CheckConstraint(
            "(status = 'REJECTED') = (rejection_reason IS NOT NULL)", name=op.f("ck_returns_rejection_reason")
        ),
        sa.CheckConstraint(
            "credit_note_id IS NULL OR (status = 'COMPLETED' AND total_credit > 0)",
            name=op.f("ck_returns_credit_note_completed"),
        ),
        sa.CheckConstraint(
            "reason_code <> 'OTHER' OR length(trim(coalesce(note, ''))) > 0", name=op.f("ck_returns_other_needs_note")
        ),
        sa.CheckConstraint(
            "reason_code IN ('DAMAGED','EXPIRED','WRONG_ITEM','NOT_ORDERED','QUALITY','OTHER')",
            name=op.f("ck_returns_reason_code"),
        ),
        sa.CheckConstraint("source IN ('STORE_REQUEST','DISPUTE')", name=op.f("ck_returns_source")),
        sa.CheckConstraint(
            "status IN ('REQUESTED','APPROVED','REJECTED','CANCELLED','RECEIVED','COMPLETED')",
            name=op.f("ck_returns_status"),
        ),
        sa.CheckConstraint("total_credit IS NULL OR total_credit >= 0", name=op.f("ck_returns_total_credit")),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], name=op.f("fk_returns_approved_by_users")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_returns_company_id_companies")),
        sa.ForeignKeyConstraint(["completed_by"], ["users.id"], name=op.f("fk_returns_completed_by_users")),
        sa.ForeignKeyConstraint(
            ["credit_note_id"], ["credit_notes.id"], name=op.f("fk_returns_credit_note_id_credit_notes")
        ),
        sa.ForeignKeyConstraint(["dispute_id"], ["disputes.id"], name=op.f("fk_returns_dispute_id_disputes")),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_returns_order_id_orders")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_returns_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["received_by"], ["users.id"], name=op.f("fk_returns_received_by_users")),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], name=op.f("fk_returns_requested_by_users")),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_returns_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
        sa.UniqueConstraint("company_id", "return_number", name=op.f("uq_returns_company_id_return_number")),
    )
    op.create_index(
        "ix_returns_company_status_created", "returns", ["company_id", "status", "created_at"], unique=False
    )
    op.create_index("ix_returns_partnership_created", "returns", ["partnership_id", "created_at"], unique=False)
    op.create_index("ix_returns_store_created", "returns", ["store_id", "created_at"], unique=False)
    op.create_index(
        "uq_returns_open_order",
        "returns",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('REQUESTED','APPROVED','RECEIVED')"),
    )
    op.create_table(
        "return_items",
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("approved_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("received_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("accepted_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("restock_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("line_credit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "accepted_quantity IS NULL OR (received_quantity IS NOT NULL AND accepted_quantity >= 0 AND accepted_quantity <= received_quantity)",
            name=op.f("ck_return_items_accepted_range"),
        ),
        sa.CheckConstraint(
            "approved_quantity IS NULL OR (approved_quantity >= 0 AND approved_quantity <= requested_quantity)",
            name=op.f("ck_return_items_approved_range"),
        ),
        sa.CheckConstraint("line_credit IS NULL OR line_credit >= 0", name=op.f("ck_return_items_line_credit")),
        sa.CheckConstraint(
            "received_quantity IS NULL OR (approved_quantity IS NOT NULL AND received_quantity >= 0 AND received_quantity <= approved_quantity)",
            name=op.f("ck_return_items_received_range"),
        ),
        sa.CheckConstraint("requested_quantity > 0", name=op.f("ck_return_items_requested_positive")),
        sa.CheckConstraint(
            "restock_quantity IS NULL OR (accepted_quantity IS NOT NULL AND restock_quantity >= 0 AND restock_quantity <= accepted_quantity)",
            name=op.f("ck_return_items_restock_range"),
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"], ["order_items.id"], name=op.f("fk_return_items_order_item_id_order_items")
        ),
        sa.ForeignKeyConstraint(["return_id"], ["returns.id"], name=op.f("fk_return_items_return_id_returns")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_items")),
        sa.UniqueConstraint("return_id", "order_item_id", name=op.f("uq_return_items_return_id_order_item_id")),
    )
    op.create_index("ix_return_items_return", "return_items", ["return_id"], unique=False)
    op.create_table(
        "return_status_history",
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("actor_type IN ('USER','SYSTEM')", name=op.f("ck_return_status_history_actor_type")),
        sa.CheckConstraint(
            "to_status IN ('REQUESTED','APPROVED','REJECTED','CANCELLED','RECEIVED','COMPLETED')",
            name=op.f("ck_return_status_history_to_status"),
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_return_status_history_actor_id_users")),
        sa.ForeignKeyConstraint(["return_id"], ["returns.id"], name=op.f("fk_return_status_history_return_id_returns")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_status_history")),
    )
    op.create_index("ix_return_history_created", "return_status_history", ["return_id", "created_at"], unique=False)
    # Added once `returns` exists: a dispute resolved into a return points back at it (DSP-022).
    op.create_foreign_key(op.f("fk_disputes_return_id_returns"), "disputes", "returns", ["return_id"], ["id"])
    _install_protection()
    # ### end Alembic commands ###


def downgrade() -> None:
    for trigger, table in (
        ("returns_protection", "returns"),
        ("returns_party", "returns"),
        ("return_items_protection", "return_items"),
        ("return_history_protection", "return_status_history"),
        ("disputes_protection", "disputes"),
        ("disputes_party", "disputes"),
        ("dispute_messages_protection", "dispute_messages"),
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
    for function in ("protect_return", "protect_return_item", "protect_dispute"):
        op.execute(f"DROP FUNCTION IF EXISTS {function}()")
    # The dispute -> return reference must go before `returns` can be dropped.
    op.drop_constraint(op.f("fk_disputes_return_id_returns"), "disputes", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_return_history_created", table_name="return_status_history")
    op.drop_table("return_status_history")
    op.drop_index("ix_return_items_return", table_name="return_items")
    op.drop_table("return_items")
    op.drop_index(
        "uq_returns_open_order",
        table_name="returns",
        postgresql_where=sa.text("status IN ('REQUESTED','APPROVED','RECEIVED')"),
    )
    op.drop_index("ix_returns_store_created", table_name="returns")
    op.drop_index("ix_returns_partnership_created", table_name="returns")
    op.drop_index("ix_returns_company_status_created", table_name="returns")
    op.drop_table("returns")
    op.drop_index("ix_dispute_messages_created", table_name="dispute_messages")
    op.drop_table("dispute_messages")
    op.drop_index(
        "uq_disputes_open_order", table_name="disputes", postgresql_where=sa.text("status IN ('OPEN','UNDER_REVIEW')")
    )
    op.drop_index("ix_disputes_store_created", table_name="disputes")
    op.drop_index("ix_disputes_partnership_created", table_name="disputes")
    op.drop_index("ix_disputes_company_status_created", table_name="disputes")
    op.drop_table("disputes")
    # ### end Alembic commands ###


def _install_protection() -> None:
    # A return progresses through its state machine, but its identity and the facts of each
    # step are written once. A terminal return or dispute is final: the credit note, the
    # restock movement and the audit trail behind it cannot be re-explained afterwards.
    op.execute("""
        CREATE FUNCTION protect_return() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE mutable text[] := ARRAY['status','approved_by','received_by','completed_by',
          'rejection_reason','cancel_reason','total_credit','credit_note_id',
          'approved_at','received_at','completed_at','updated_at','version'];
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'returns cannot be deleted'; END IF;
          IF OLD.status IN ('REJECTED','CANCELLED','COMPLETED')
          THEN RAISE EXCEPTION 'a finished return is immutable'; END IF;
          IF (to_jsonb(NEW) - mutable) IS DISTINCT FROM (to_jsonb(OLD) - mutable)
          THEN RAISE EXCEPTION 'return identity is immutable'; END IF;
          RETURN NEW;
        END $$
    """)
    op.execute("""
        CREATE FUNCTION protect_return_item() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE mutable text[] := ARRAY['approved_quantity','received_quantity',
          'accepted_quantity','restock_quantity','line_credit'];
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'return items cannot be deleted'; END IF;
          IF (to_jsonb(NEW) - mutable) IS DISTINCT FROM (to_jsonb(OLD) - mutable)
          THEN RAISE EXCEPTION 'return item identity is immutable'; END IF;
          -- Each step of the quantity ladder is decided once, so an approved or accepted
          -- quantity can be filled in but never rewritten.
          IF (OLD.approved_quantity IS NOT NULL AND NEW.approved_quantity IS DISTINCT FROM OLD.approved_quantity)
             OR (OLD.received_quantity IS NOT NULL AND NEW.received_quantity IS DISTINCT FROM OLD.received_quantity)
             OR (OLD.accepted_quantity IS NOT NULL AND NEW.accepted_quantity IS DISTINCT FROM OLD.accepted_quantity)
             OR (OLD.restock_quantity IS NOT NULL AND NEW.restock_quantity IS DISTINCT FROM OLD.restock_quantity)
             OR (OLD.line_credit IS NOT NULL AND NEW.line_credit IS DISTINCT FROM OLD.line_credit)
          THEN RAISE EXCEPTION 'return quantities are decided once'; END IF;
          RETURN NEW;
        END $$
    """)
    op.execute("""
        CREATE FUNCTION protect_dispute() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE mutable text[] := ARRAY['status','resolution_type','resolution_note',
          'pending_adjustment_id','adjustment_id','return_id','resolved_by','resolved_at',
          'updated_at','version'];
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'disputes cannot be deleted'; END IF;
          IF OLD.status IN ('RESOLVED','REJECTED','WITHDRAWN')
          THEN RAISE EXCEPTION 'a closed dispute is immutable'; END IF;
          IF (to_jsonb(NEW) - mutable) IS DISTINCT FROM (to_jsonb(OLD) - mutable)
          THEN RAISE EXCEPTION 'dispute identity is immutable'; END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER returns_protection BEFORE UPDATE OR DELETE ON returns "
        "FOR EACH ROW EXECUTE FUNCTION protect_return()"
    )
    op.execute(
        "CREATE TRIGGER return_items_protection BEFORE UPDATE OR DELETE ON return_items "
        "FOR EACH ROW EXECUTE FUNCTION protect_return_item()"
    )
    op.execute(
        "CREATE TRIGGER disputes_protection BEFORE UPDATE OR DELETE ON disputes "
        "FOR EACH ROW EXECUTE FUNCTION protect_dispute()"
    )
    # Status history and dispute messages are facts: `forbid_mutation` is the core P00 guard.
    op.execute(
        "CREATE TRIGGER return_history_protection BEFORE UPDATE OR DELETE ON return_status_history "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER dispute_messages_protection BEFORE UPDATE OR DELETE ON dispute_messages "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    # The same ownership rule the finance records use: a P10 record cannot be filed under a
    # company/store pair that is not its own partnership (the function is installed by P09,
    # which this revision already requires).
    for table in ("returns", "disputes"):
        op.execute(
            f"CREATE TRIGGER {table}_party BEFORE INSERT OR UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_finance_party()"
        )
