"""subscriptions

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-04 13:51:01.863826
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # UUIDv7 bootstrap IDs, without requiring PostgreSQL 18's uuidv7().
    # This helper exists only for the migration and is dropped below.
    op.execute("""
        CREATE FUNCTION p03_uuid7() RETURNS uuid LANGUAGE plpgsql VOLATILE AS $$
        DECLARE bytes bytea;
        BEGIN
          bytes := decode(lpad(to_hex(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint), 12, '0'), 'hex')
            || substring(uuid_send(gen_random_uuid()) FROM 7);
          bytes := set_byte(bytes, 6, (get_byte(bytes, 6) & 15) | 112);
          bytes := set_byte(bytes, 8, (get_byte(bytes, 8) & 63) | 128);
          RETURN encode(bytes, 'hex')::uuid;
        END $$
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_plans",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_monthly", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="TJS", nullable=False),
        sa.Column("max_active_stores", sa.Integer(), nullable=True),
        sa.Column("max_users", sa.Integer(), nullable=True),
        sa.Column("max_products", sa.Integer(), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency = 'TJS'", name=op.f("ck_subscription_plans_currency")),
        sa.CheckConstraint(
            "max_active_stores IS NULL OR max_active_stores > 0", name=op.f("ck_subscription_plans_stores_positive")
        ),
        sa.CheckConstraint(
            "max_products IS NULL OR max_products > 0", name=op.f("ck_subscription_plans_products_positive")
        ),
        sa.CheckConstraint("max_users IS NULL OR max_users > 0", name=op.f("ck_subscription_plans_users_positive")),
        sa.CheckConstraint("price_monthly >= 0", name=op.f("ck_subscription_plans_price_nonnegative")),
        sa.CheckConstraint("version > 0", name=op.f("ck_subscription_plans_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_subscription_plans_code")),
    )
    op.create_table(
        "plan_change_requests",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("requested_plan_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("handled_by", sa.Uuid(), nullable=True),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('PENDING','DONE','DISMISSED')", name=op.f("ck_plan_change_requests_status")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_plan_change_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["handled_by"], ["users.id"], name=op.f("fk_plan_change_requests_handled_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_plan_change_requests_requested_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["requested_plan_id"],
            ["subscription_plans.id"],
            name=op.f("fk_plan_change_requests_requested_plan_id_subscription_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_change_requests")),
    )
    op.create_index(op.f("ix_plan_change_requests_company_id"), "plan_change_requests", ["company_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("soft_block_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('TRIAL','ACTIVE','GRACE','SOFT_BLOCK','FULL_BLOCK','CANCELLED')",
            name=op.f("ck_subscriptions_status"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_subscriptions_version_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_subscriptions_company_id_companies"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscription_plans.id"],
            name=op.f("fk_subscriptions_plan_id_subscription_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("company_id", name=op.f("uq_subscriptions_company_id")),
    )
    op.create_index("ix_subscriptions_status_grace", "subscriptions", ["status", "grace_ends_at"], unique=False)
    op.create_index("ix_subscriptions_status_period", "subscriptions", ["status", "current_period_end"], unique=False)
    op.create_index("ix_subscriptions_status_soft", "subscriptions", ["status", "soft_block_ends_at"], unique=False)
    op.create_index("ix_subscriptions_status_trial", "subscriptions", ["status", "trial_ends_at"], unique=False)
    op.create_table(
        "subscription_payments",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("months", sa.SmallInteger(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency = 'TJS'", name=op.f("ck_subscription_payments_currency")),
        sa.CheckConstraint("method IN ('CASH','BANK_TRANSFER')", name=op.f("ck_subscription_payments_method")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_subscription_payments_amount_positive")),
        sa.CheckConstraint("months BETWEEN 1 AND 12", name=op.f("ck_subscription_payments_months")),
        sa.CheckConstraint("period_end > period_start", name=op.f("ck_subscription_payments_period")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscription_plans.id"],
            name=op.f("fk_subscription_payments_plan_id_subscription_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["users.id"], name=op.f("fk_subscription_payments_recorded_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_payments_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_payments")),
    )
    op.create_index(
        op.f("ix_subscription_payments_subscription_id"), "subscription_payments", ["subscription_id"], unique=False
    )
    op.create_table(
        "subscription_reminders",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("anchor_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_reminders_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_reminders")),
    )
    op.create_index(
        "uq_subscription_reminders_anchor",
        "subscription_reminders",
        ["subscription_id", "kind", "anchor_at"],
        unique=True,
    )
    op.create_table(
        "subscription_status_history",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ('TRIAL','ACTIVE','GRACE','SOFT_BLOCK','FULL_BLOCK','CANCELLED')",
            name=op.f("ck_subscription_status_history_from_status"),
        ),
        sa.CheckConstraint(
            "to_status IN ('TRIAL','ACTIVE','GRACE','SOFT_BLOCK','FULL_BLOCK','CANCELLED')",
            name=op.f("ck_subscription_status_history_to_status"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_subscription_status_history_actor_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_status_history_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_status_history")),
    )
    op.create_index(
        op.f("ix_subscription_status_history_subscription_id"),
        "subscription_status_history",
        ["subscription_id"],
        unique=False,
    )
    op.execute("""
        INSERT INTO subscription_plans
          (id, code, name, price_monthly, max_active_stores, max_users, max_products, sort_order)
        VALUES
          (p03_uuid7(), 'START', '{"tg":"Оғоз","ru":"Старт","en":"Start"}', 300, 30, 5, 500, 1),
          (p03_uuid7(), 'STANDARD', '{"tg":"Стандарт","ru":"Стандарт","en":"Standard"}', 700, 150, 15, 3000, 2),
          (p03_uuid7(), 'LARGE', '{"tg":"Калон","ru":"Большой","en":"Large"}', 1500, NULL, NULL, NULL, 3)
    """)
    # Existing companies receive the same fresh trial as new companies at rollout.
    op.execute("""
        INSERT INTO subscriptions (id, company_id, plan_id, status, trial_ends_at, status_changed_at)
        SELECT p03_uuid7(), c.id, p.id, 'TRIAL', now() + interval '14 days', now()
        FROM companies c CROSS JOIN subscription_plans p WHERE p.code = 'STANDARD'
    """)
    op.execute("""
        INSERT INTO subscription_status_history (id, subscription_id, from_status, to_status, reason)
        SELECT p03_uuid7(), id, NULL, 'TRIAL', 'P03 rollout trial' FROM subscriptions
    """)
    op.execute("""
        INSERT INTO audit_logs (id, actor_type, org_id, action, entity_type, entity_id, new_data, reason)
        SELECT p03_uuid7(), 'SYSTEM', company_id, 'subscription.status_changed', 'subscription', id,
          '{"status":"TRIAL"}'::jsonb, 'P03 rollout trial' FROM subscriptions
    """)
    op.execute("""
        INSERT INTO outbox_events (id, event_type, org_id, payload, next_attempt_at)
        SELECT p03_uuid7(), 'SUBSCRIPTION_STATUS_CHANGED', company_id,
          jsonb_build_object('subscription_id', id, 'company_id', company_id,
            'from_status', NULL, 'to_status', 'TRIAL', 'reason', 'P03 rollout trial'), now()
        FROM subscriptions
    """)
    for table in ("subscription_payments", "subscription_status_history"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
        )
    op.execute("""
        CREATE FUNCTION subscription_payment_superadmin() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM users WHERE id = NEW.recorded_by AND is_superadmin) THEN
            RAISE EXCEPTION 'subscription payment recorder must be SUPERADMIN' USING ERRCODE = '23514';
          END IF;
          RETURN NEW;
        END $$;
    """)
    op.execute("""CREATE TRIGGER subscription_payment_superadmin BEFORE INSERT ON subscription_payments
          FOR EACH ROW EXECUTE FUNCTION subscription_payment_superadmin()""")
    op.execute("DROP FUNCTION p03_uuid7()")


def downgrade() -> None:
    op.execute("DROP TRIGGER subscription_payment_superadmin ON subscription_payments")
    op.execute("DROP FUNCTION subscription_payment_superadmin()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_status_history_subscription_id"), table_name="subscription_status_history")
    op.drop_table("subscription_status_history")
    op.drop_index("uq_subscription_reminders_anchor", table_name="subscription_reminders")
    op.drop_table("subscription_reminders")
    op.drop_index(op.f("ix_subscription_payments_subscription_id"), table_name="subscription_payments")
    op.drop_table("subscription_payments")
    op.drop_index("ix_subscriptions_status_trial", table_name="subscriptions")
    op.drop_index("ix_subscriptions_status_soft", table_name="subscriptions")
    op.drop_index("ix_subscriptions_status_period", table_name="subscriptions")
    op.drop_index("ix_subscriptions_status_grace", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_plan_change_requests_company_id"), table_name="plan_change_requests")
    op.drop_table("plan_change_requests")
    op.drop_table("subscription_plans")
    # ### end Alembic commands ###
