"""P07 orders carts and immutable snapshots

Revision ID: f78d0fa3dbff
Revises: 2125e5a871b4
Create Date: 2026-10-06 12:47:05.040061
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "f78d0fa3dbff"
down_revision = "2125e5a871b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_carts_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_carts_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
        sa.UniqueConstraint("partnership_id", "user_id", name=op.f("uq_carts_partnership_id_user_id")),
    )
    op.create_table(
        "orders",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="TJS", nullable=False),
        sa.Column("requested_subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("discount_reason", sa.Text(), nullable=True),
        sa.Column("delivery_fee", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("terms_id", sa.Uuid(), nullable=True),
        sa.Column("terms_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("delivery_address", sa.String(length=500), nullable=False),
        sa.Column("delivery_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("delivery_longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("store_note", sa.Text(), nullable=True),
        sa.Column("company_note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("credit_override_reason", sa.Text(), nullable=True),
        sa.Column("minimum_override_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency = 'TJS'", name=op.f("ck_orders_currency")),
        sa.CheckConstraint("source IN ('STORE','COMPANY_ON_BEHALF')", name=op.f("ck_orders_source")),
        sa.CheckConstraint(
            "status IN ('NEW','VIEWED','CONFIRMED','PARTIALLY_CONFIRMED','ASSEMBLING','READY_FOR_DELIVERY','IN_TRANSIT','DELIVERED','DELIVERY_FAILED','DISPUTED','COMPLETED','REJECTED','CANCELLED')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint("discount = 0 OR length(trim(discount_reason)) > 0", name=op.f("ck_orders_discount_reason")),
        sa.CheckConstraint(
            "discount >= 0 AND (subtotal IS NULL OR discount <= subtotal)", name=op.f("ck_orders_discount")
        ),
        sa.CheckConstraint(
            "requested_subtotal >= 0 AND (subtotal IS NULL OR subtotal >= 0) AND delivery_fee >= 0",
            name=op.f("ck_orders_amounts"),
        ),
        sa.CheckConstraint(
            "total IS NULL OR (subtotal IS NOT NULL AND total = subtotal - discount + delivery_fee)",
            name=op.f("ck_orders_total"),
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_orders_company_id_companies")),
        sa.ForeignKeyConstraint(["confirmed_by"], ["users.id"], name=op.f("fk_orders_confirmed_by_users")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_orders_created_by_users")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_orders_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_orders_store_id_stores")),
        sa.ForeignKeyConstraint(
            ["terms_id"], ["partnership_terms.id"], name=op.f("fk_orders_terms_id_partnership_terms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("company_id", "order_number", name=op.f("uq_orders_company_id_order_number")),
        sa.UniqueConstraint(
            "id",
            "company_id",
            "store_id",
            "partnership_id",
            name=op.f("uq_orders_id_company_id_store_id_partnership_id"),
        ),
    )
    op.create_index("ix_orders_company_status_created", "orders", ["company_id", "status", "created_at"], unique=False)
    op.create_index(
        "ix_orders_number_trgm",
        "orders",
        ["order_number"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"order_number": "gin_trgm_ops"},
    )
    op.create_index("ix_orders_partnership_status", "orders", ["partnership_id", "status"], unique=False)
    op.create_index("ix_orders_store_created", "orders", ["store_id", "created_at"], unique=False)
    op.create_table(
        "cart_items",
        sa.Column("cart_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cart_items_quantity")),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("fk_cart_items_cart_id_carts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"], ["product_units.id"], name=op.f("fk_cart_items_product_unit_id_product_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("cart_id", "product_unit_id", name=op.f("uq_cart_items_cart_id_product_unit_id")),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("product_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("sku_snapshot", sa.String(length=64), nullable=False),
        sa.Column("unit_code_snapshot", sa.String(length=16), nullable=False),
        sa.Column("unit_name_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit_coefficient_snapshot", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("allow_fraction_snapshot", sa.Boolean(), nullable=False),
        sa.Column("base_unit_snapshot", sa.String(length=8), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("confirmed_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "confirmed_quantity IS NULL OR (confirmed_quantity >= 0 AND confirmed_quantity <= requested_quantity)",
            name=op.f("ck_order_items_confirmed"),
        ),
        sa.CheckConstraint(
            "line_total = round(coalesce(confirmed_quantity, requested_quantity) * unit_price, 2)",
            name=op.f("ck_order_items_line_total"),
        ),
        sa.CheckConstraint(
            "requested_quantity > 0 AND unit_coefficient_snapshot > 0 AND unit_price > 0",
            name=op.f("ck_order_items_positive"),
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders")),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products")),
        sa.ForeignKeyConstraint(
            ["product_unit_id"], ["product_units.id"], name=op.f("fk_order_items_product_unit_id_product_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint("order_id", "product_unit_id", name=op.f("uq_order_items_order_id_product_unit_id")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("actor_type IN ('USER','SYSTEM')", name=op.f("ck_order_status_history_actor_type")),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_order_status_history_actor_id_users")),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_order_status_history_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index("ix_order_history_created", "order_status_history", ["order_id", "created_at"], unique=False)
    op.execute(
        "CREATE TRIGGER order_history_immutable BEFORE UPDATE OR DELETE ON order_status_history "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute("""
        CREATE FUNCTION protect_order_item() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'order items are immutable'; END IF;
          IF TG_OP = 'UPDATE' THEN
            IF (to_jsonb(NEW) - 'confirmed_quantity' - 'line_total') IS DISTINCT FROM
               (to_jsonb(OLD) - 'confirmed_quantity' - 'line_total') OR
               (OLD.confirmed_quantity IS NOT NULL AND NEW.confirmed_quantity IS DISTINCT FROM OLD.confirmed_quantity)
            THEN RAISE EXCEPTION 'order item snapshot is immutable'; END IF;
          ELSE
            IF NOT EXISTS (SELECT 1 FROM orders o JOIN products p ON p.company_id = o.company_id
                JOIN product_units u ON u.product_id = p.id
                WHERE o.id = NEW.order_id AND p.id = NEW.product_id AND u.id = NEW.product_unit_id)
            THEN RAISE EXCEPTION 'order item ownership mismatch'; END IF;
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER order_item_protection BEFORE INSERT OR UPDATE OR DELETE ON order_items "
        "FOR EACH ROW EXECUTE FUNCTION protect_order_item()"
    )
    op.execute("""
        CREATE FUNCTION protect_order() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM partnerships p WHERE p.id = NEW.partnership_id AND
              p.company_id = NEW.company_id AND p.store_id = NEW.store_id)
          THEN RAISE EXCEPTION 'order partnership ownership mismatch'; END IF;
          IF NEW.terms_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM partnership_terms t
              WHERE t.id = NEW.terms_id AND t.partnership_id = NEW.partnership_id)
          THEN RAISE EXCEPTION 'order terms ownership mismatch'; END IF;
          IF TG_OP = 'UPDATE' THEN
            IF ROW(NEW.id, NEW.company_id, NEW.store_id, NEW.partnership_id, NEW.order_number,
                NEW.source, NEW.currency, NEW.requested_subtotal, NEW.delivery_address,
                NEW.delivery_latitude, NEW.delivery_longitude, NEW.created_by, NEW.created_at, NEW.store_note)
              IS DISTINCT FROM ROW(OLD.id, OLD.company_id, OLD.store_id, OLD.partnership_id, OLD.order_number,
                OLD.source, OLD.currency, OLD.requested_subtotal, OLD.delivery_address,
                OLD.delivery_latitude, OLD.delivery_longitude, OLD.created_by, OLD.created_at, OLD.store_note)
            THEN RAISE EXCEPTION 'order creation snapshot is immutable'; END IF;
            IF OLD.terms_id IS NOT NULL AND ROW(NEW.terms_id, NEW.terms_snapshot, NEW.subtotal,
                NEW.discount, NEW.discount_reason, NEW.delivery_fee, NEW.total, NEW.confirmed_by, NEW.confirmed_at)
              IS DISTINCT FROM ROW(OLD.terms_id, OLD.terms_snapshot, OLD.subtotal,
                OLD.discount, OLD.discount_reason, OLD.delivery_fee, OLD.total, OLD.confirmed_by, OLD.confirmed_at)
            THEN RAISE EXCEPTION 'order confirmation snapshot is immutable'; END IF;
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER order_protection BEFORE INSERT OR UPDATE ON orders "
        "FOR EACH ROW EXECUTE FUNCTION protect_order()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER order_protection ON orders")
    op.execute("DROP TRIGGER order_item_protection ON order_items")
    op.execute("DROP FUNCTION protect_order()")
    op.execute("DROP FUNCTION protect_order_item()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_order_history_created", table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_table("cart_items")
    op.drop_index("ix_orders_store_created", table_name="orders")
    op.drop_index("ix_orders_partnership_status", table_name="orders")
    op.drop_index(
        "ix_orders_number_trgm",
        table_name="orders",
        postgresql_using="gin",
        postgresql_ops={"order_number": "gin_trgm_ops"},
    )
    op.drop_index("ix_orders_company_status_created", table_name="orders")
    op.drop_table("orders")
    op.drop_table("carts")
    # ### end Alembic commands ###
