"""P06 partnerships and immutable terms

Revision ID: 2125e5a871b4
Revises: 20261005_0020
Create Date: 2026-10-06 11:16:30.874484
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "2125e5a871b4"
down_revision = "20261005_0020"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partnerships",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("initiated_by_side", sa.String(length=8), nullable=False),
        sa.Column("initiated_by", sa.Uuid(), nullable=False),
        sa.Column("customer_code", sa.String(length=32), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("initiated_by_side IN ('COMPANY','STORE')", name=op.f("ck_partnerships_initiated_by_side")),
        sa.CheckConstraint(
            "status IN ('PENDING','ACTIVE','SUSPENDED','TERMINATED','DECLINED','CANCELLED')",
            name=op.f("ck_partnerships_status"),
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_partnerships_company_id_companies")),
        sa.ForeignKeyConstraint(["initiated_by"], ["users.id"], name=op.f("fk_partnerships_initiated_by_users")),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_partnerships_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partnerships")),
    )
    op.create_index("ix_partnerships_company_status", "partnerships", ["company_id", "status"], unique=False)
    op.create_index("ix_partnerships_store_status", "partnerships", ["store_id", "status"], unique=False)
    op.create_index(
        "uq_partnership_customer_code",
        "partnerships",
        ["company_id", "customer_code"],
        unique=True,
        postgresql_where=sa.text("customer_code IS NOT NULL"),
    )
    op.create_index(
        "uq_partnership_open",
        "partnerships",
        ["company_id", "store_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING','ACTIVE','SUSPENDED')"),
    )
    op.create_table(
        "partnership_terms",
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("price_list_id", sa.Uuid(), nullable=False),
        sa.Column("credit_limit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("credit_days", sa.SmallInteger(), nullable=False),
        sa.Column("payment_methods", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("minimum_order_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("delivery_fee", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("free_delivery_threshold", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("return_days", sa.SmallInteger(), server_default="14", nullable=False),
        sa.Column("dispute_window_hours", sa.SmallInteger(), server_default="48", nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "cardinality(payment_methods) > 0 AND payment_methods <@ ARRAY['CASH','BANK_TRANSFER']::varchar[] AND array_position(payment_methods, NULL) IS NULL",
            name=op.f("ck_partnership_terms_payment_methods"),
        ),
        sa.CheckConstraint("credit_days BETWEEN 0 AND 180", name=op.f("ck_partnership_terms_credit_days")),
        sa.CheckConstraint(
            "credit_limit >= 0 AND minimum_order_amount >= 0 AND delivery_fee >= 0",
            name=op.f("ck_partnership_terms_money"),
        ),
        sa.CheckConstraint(
            "dispute_window_hours BETWEEN 1 AND 168", name=op.f("ck_partnership_terms_dispute_window_hours")
        ),
        sa.CheckConstraint(
            "free_delivery_threshold IS NULL OR free_delivery_threshold > 0",
            name=op.f("ck_partnership_terms_free_delivery_threshold"),
        ),
        sa.CheckConstraint("return_days BETWEEN 0 AND 60", name=op.f("ck_partnership_terms_return_days")),
        sa.CheckConstraint("version_no >= 1", name=op.f("ck_partnership_terms_version_no")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_partnership_terms_created_by_users")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_partnership_terms_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(
            ["price_list_id"], ["price_lists.id"], name=op.f("fk_partnership_terms_price_list_id_price_lists")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partnership_terms")),
        sa.UniqueConstraint(
            "partnership_id", "version_no", name=op.f("uq_partnership_terms_partnership_id_version_no")
        ),
    )
    op.create_index(
        "ix_partnership_terms_effective", "partnership_terms", ["partnership_id", "effective_from"], unique=False
    )
    op.execute(
        "CREATE TRIGGER partnership_terms_immutable BEFORE UPDATE OR DELETE ON partnership_terms "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute("""
        CREATE FUNCTION validate_partnership_terms_company() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM partnerships p JOIN price_lists l ON l.company_id = p.company_id
                WHERE p.id = NEW.partnership_id AND l.id = NEW.price_list_id AND l.is_active
            ) THEN
                RAISE EXCEPTION 'partnership_terms_price_list_company' USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END $$;
    """)
    op.execute(
        "CREATE TRIGGER partnership_terms_company BEFORE INSERT ON partnership_terms "
        "FOR EACH ROW EXECUTE FUNCTION validate_partnership_terms_company()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER partnership_terms_company ON partnership_terms")
    op.execute("DROP FUNCTION validate_partnership_terms_company()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_partnership_terms_effective", table_name="partnership_terms")
    op.drop_table("partnership_terms")
    op.drop_index(
        "uq_partnership_open",
        table_name="partnerships",
        postgresql_where=sa.text("status IN ('PENDING','ACTIVE','SUSPENDED')"),
    )
    op.drop_index(
        "uq_partnership_customer_code", table_name="partnerships", postgresql_where=sa.text("customer_code IS NOT NULL")
    )
    op.drop_index("ix_partnerships_store_status", table_name="partnerships")
    op.drop_index("ix_partnerships_company_status", table_name="partnerships")
    op.drop_table("partnerships")
    # ### end Alembic commands ###
