"""P09 financial records and immutable posting constraints."""

import sqlalchemy as sa
from alembic import op

revision = "20261008_0024"
down_revision = "581393db10d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adjustments",
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), server_default="MANUAL", nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="PENDING_APPROVAL", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("self_approved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("source IN ('MANUAL','DISPUTE')", name=op.f("ck_adjustments_source")),
        sa.CheckConstraint("status IN ('PENDING_APPROVAL','APPROVED','REJECTED')", name=op.f("ck_adjustments_status")),
        sa.CheckConstraint("type IN ('DEBIT','CREDIT','REFUND')", name=op.f("ck_adjustments_type")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_adjustments_amount_positive")),
        sa.CheckConstraint("length(btrim(reason)) >= 10", name=op.f("ck_adjustments_reason")),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], name=op.f("fk_adjustments_approved_by_users")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_adjustments_created_by_users")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_adjustments_partnership_id_partnerships")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adjustments")),
    )
    op.create_index("ix_adjustments_partnership_status", "adjustments", ["partnership_id", "status"], unique=False)
    op.create_table(
        "charges",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(allocated_amount = 0 AND status = 'OPEN') OR (allocated_amount > 0 AND allocated_amount < amount AND status = 'PARTIALLY_PAID') OR (allocated_amount = amount AND status = 'PAID')",
            name=op.f("ck_charges_status_matches_allocation"),
        ),
        sa.CheckConstraint("(status = 'PAID') = (paid_at IS NOT NULL)", name=op.f("ck_charges_paid_at_matches_status")),
        sa.CheckConstraint("kind IN ('ORDER','ADJUSTMENT','REFUND')", name=op.f("ck_charges_kind")),
        sa.CheckConstraint(
            "allocated_amount >= 0 AND allocated_amount <= amount", name=op.f("ck_charges_allocated_range")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_charges_amount_positive")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_charges_company_id_companies")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_charges_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_charges_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charges")),
        sa.UniqueConstraint("kind", "source_id", name=op.f("uq_charges_kind_source_id")),
    )
    op.create_index(
        "ix_charges_partnership_status_due_created",
        "charges",
        ["partnership_id", "status", "due_date", "created_at"],
        unique=False,
    )
    op.create_table(
        "credit_notes",
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("source_type", sa.String(length=16), server_default="RETURN", nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("source_type = 'RETURN'", name=op.f("ck_credit_notes_source_type")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_credit_notes_amount_positive")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_credit_notes_created_by_users")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_credit_notes_partnership_id_partnerships")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_notes")),
        sa.UniqueConstraint("source_id", name=op.f("uq_credit_notes_source_id")),
    )
    op.create_index(op.f("ix_credit_notes_partnership_id"), "credit_notes", ["partnership_id"], unique=False)
    op.create_table(
        "credits",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('PAYMENT','CREDIT_NOTE','ADJUSTMENT')", name=op.f("ck_credits_kind")),
        sa.CheckConstraint(
            "allocated_amount >= 0 AND allocated_amount <= amount", name=op.f("ck_credits_allocated_range")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_credits_amount_positive")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_credits_company_id_companies")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_credits_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_credits_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credits")),
        sa.UniqueConstraint("kind", "source_id", name=op.f("uq_credits_kind_source_id")),
    )
    op.create_index("ix_credits_partnership_created", "credits", ["partnership_id", "created_at", "id"], unique=False)
    op.create_table(
        "ledger_entries",
        sa.Column("entry_type", sa.String(length=24), nullable=False),
        sa.Column("direction", sa.String(length=6), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(direction = 'DEBIT' AND entry_type IN ('CHARGE','ADJUSTMENT_DEBIT','REFUND')) OR (direction = 'CREDIT' AND entry_type IN ('PAYMENT','CREDIT_NOTE','ADJUSTMENT_CREDIT'))",
            name=op.f("ck_ledger_entries_entry_direction"),
        ),
        sa.CheckConstraint(
            "source_type IN ('ORDER','PAYMENT','CREDIT_NOTE','ADJUSTMENT')", name=op.f("ck_ledger_entries_source_type")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_ledger_entries_amount_positive")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_ledger_entries_company_id_companies")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_ledger_entries_created_by_users")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_ledger_entries_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_ledger_entries_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
        sa.UniqueConstraint("entry_type", "source_id", name=op.f("uq_ledger_entries_entry_type_source_id")),
    )
    op.create_index(
        "ix_ledger_entries_partnership_created_id",
        "ledger_entries",
        ["partnership_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_issues",
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("check_code", sa.String(length=64), nullable=False),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("actual", sa.Text(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_reconciliation_issues_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], name=op.f("fk_reconciliation_issues_resolved_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_issues")),
    )
    op.create_index(
        "ix_reconciliation_issues_unresolved", "reconciliation_issues", ["resolved_at", "detected_at"], unique=False
    )
    op.create_table(
        "allocations",
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("charge_id", sa.Uuid(), nullable=False),
        sa.Column("credit_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_allocations_amount_positive")),
        sa.ForeignKeyConstraint(["charge_id"], ["charges.id"], name=op.f("fk_allocations_charge_id_charges")),
        sa.ForeignKeyConstraint(["credit_id"], ["credits.id"], name=op.f("fk_allocations_credit_id_credits")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_allocations_partnership_id_partnerships")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    op.create_index(op.f("ix_allocations_charge_id"), "allocations", ["charge_id"], unique=False)
    op.create_index(op.f("ix_allocations_credit_id"), "allocations", ["credit_id"], unique=False)
    op.create_index(op.f("ix_allocations_partnership_id"), "allocations", ["partnership_id"], unique=False)
    op.create_table(
        "debt_reminders",
        sa.Column("charge_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('DEBT_DUE_SOON','DEBT_OVERDUE')", name=op.f("ck_debt_reminders_kind")),
        sa.ForeignKeyConstraint(["charge_id"], ["charges.id"], name=op.f("fk_debt_reminders_charge_id_charges")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debt_reminders")),
        sa.UniqueConstraint(
            "charge_id", "kind", "anchor_date", name=op.f("uq_debt_reminders_charge_id_kind_anchor_date")
        ),
    )
    op.create_table(
        "partnership_balances",
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column("last_entry_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_entry_id"], ["ledger_entries.id"], name=op.f("fk_partnership_balances_last_entry_id_ledger_entries")
        ),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_partnership_balances_partnership_id_partnerships")
        ),
        sa.PrimaryKeyConstraint("partnership_id", name=op.f("pk_partnership_balances")),
    )
    op.create_table(
        "payments",
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column("recorded_side", sa.String(length=8), nullable=False),
        sa.Column("delivery_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("partnership_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "method <> 'BANK_TRANSFER' OR (reference IS NOT NULL AND length(btrim(reference)) > 0)",
            name=op.f("ck_payments_bank_reference"),
        ),
        sa.CheckConstraint("method IN ('CASH','BANK_TRANSFER')", name=op.f("ck_payments_method")),
        sa.CheckConstraint("recorded_side IN ('COMPANY','STORE')", name=op.f("ck_payments_recorded_side")),
        sa.CheckConstraint("status IN ('PENDING','CONFIRMED','REJECTED','CANCELLED')", name=op.f("ck_payments_status")),
        sa.CheckConstraint("amount > 0 AND amount <= 10000000.00", name=op.f("ck_payments_amount_range")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_payments_company_id_companies")),
        sa.ForeignKeyConstraint(["confirmed_by"], ["users.id"], name=op.f("fk_payments_confirmed_by_users")),
        sa.ForeignKeyConstraint(["delivery_id"], ["deliveries.id"], name=op.f("fk_payments_delivery_id_deliveries")),
        sa.ForeignKeyConstraint(
            ["partnership_id"], ["partnerships.id"], name=op.f("fk_payments_partnership_id_partnerships")
        ),
        sa.ForeignKeyConstraint(["recorded_by"], ["users.id"], name=op.f("fk_payments_recorded_by_users")),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], name=op.f("fk_payments_store_id_stores")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(
        "ix_payments_company_status_created", "payments", ["company_id", "status", "created_at"], unique=False
    )
    op.create_index("ix_payments_partnership_created", "payments", ["partnership_id", "created_at"], unique=False)
    op.create_table(
        "payment_status_history",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status = 'PENDING'", name=op.f("ck_payment_status_history_from_status")
        ),
        sa.CheckConstraint(
            "to_status IN ('PENDING','CONFIRMED','REJECTED','CANCELLED')",
            name=op.f("ck_payment_status_history_to_status"),
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_payment_status_history_actor_id_users")),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name=op.f("fk_payment_status_history_payment_id_payments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_status_history")),
    )
    op.create_index(
        op.f("ix_payment_status_history_payment_id"), "payment_status_history", ["payment_id"], unique=False
    )
    op.add_column("companies", sa.Column("debt_reminders_enabled", sa.Boolean(), server_default="true", nullable=False))
    _install_protection()
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ("charges", "credits", "payments", "ledger_entries"):
        op.execute(f"DROP TRIGGER IF EXISTS finance_party ON {table}")
    op.execute("DROP TRIGGER IF EXISTS finance_allocation_party ON allocations")
    for table in (
        "charges",
        "credits",
        "payments",
        "adjustments",
        "credit_notes",
        "ledger_entries",
        "allocations",
        "payment_status_history",
        "debt_reminders",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS finance_protection ON {table}")
    for function in (
        "protect_finance_item",
        "protect_finance_party",
        "protect_finance_allocation",
        "protect_finance_payment",
        "protect_finance_adjustment",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {function}()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "debt_reminders_enabled")
    op.drop_table("payment_status_history")
    op.drop_table("payments")
    op.drop_table("partnership_balances")
    op.drop_table("debt_reminders")
    op.drop_table("allocations")
    op.drop_table("reconciliation_issues")
    op.drop_table("ledger_entries")
    op.drop_table("credits")
    op.drop_table("credit_notes")
    op.drop_table("charges")
    op.drop_table("adjustments")
    # ### end Alembic commands ###


def _install_protection() -> None:
    # Facts are immutable; only allocation projections on debit/credit items can change.
    op.execute("""
        CREATE FUNCTION protect_finance_item() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE allowed text[];
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'financial items cannot be deleted'; END IF;
          allowed := CASE WHEN TG_TABLE_NAME = 'charges'
            THEN ARRAY['allocated_amount','status','paid_at'] ELSE ARRAY['allocated_amount'] END;
          IF (to_jsonb(NEW) - allowed) IS DISTINCT FROM (to_jsonb(OLD) - allowed)
          THEN RAISE EXCEPTION 'financial posting facts are immutable'; END IF;
          IF NEW.allocated_amount < OLD.allocated_amount
          THEN RAISE EXCEPTION 'financial allocations cannot decrease'; END IF;
          RETURN NEW;
        END $$
    """)
    op.execute("""
        CREATE FUNCTION protect_finance_party() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM partnerships p WHERE p.id = NEW.partnership_id
            AND p.company_id = NEW.company_id AND p.store_id = NEW.store_id)
          THEN RAISE EXCEPTION 'financial partnership ownership mismatch'; END IF;
          RETURN NEW;
        END $$
    """)
    for table in ("charges", "credits"):
        op.execute(
            f"CREATE TRIGGER finance_protection BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_finance_item()"
        )
    for table in ("charges", "credits", "payments", "ledger_entries"):
        op.execute(
            f"CREATE TRIGGER finance_party BEFORE INSERT OR UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_finance_party()"
        )
    for table in ("ledger_entries", "allocations", "credit_notes", "payment_status_history", "debt_reminders"):
        op.execute(
            f"CREATE TRIGGER finance_protection BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
        )
    op.execute("""
        CREATE FUNCTION protect_finance_allocation() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE charge_party uuid; credit_party uuid;
        BEGIN
          SELECT partnership_id INTO charge_party FROM charges WHERE id = NEW.charge_id FOR UPDATE;
          SELECT partnership_id INTO credit_party FROM credits WHERE id = NEW.credit_id FOR UPDATE;
          IF charge_party IS DISTINCT FROM NEW.partnership_id
             OR credit_party IS DISTINCT FROM NEW.partnership_id
          THEN RAISE EXCEPTION 'allocation partnership mismatch'; END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER finance_allocation_party BEFORE INSERT ON allocations "
        "FOR EACH ROW EXECUTE FUNCTION protect_finance_allocation()"
    )
    op.execute("""
        CREATE FUNCTION protect_finance_payment() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'payments cannot be deleted'; END IF;
          IF OLD.status <> 'PENDING' THEN RAISE EXCEPTION 'final payments are immutable'; END IF;
          IF (to_jsonb(NEW) - ARRAY['status','confirmed_by','confirmed_at','rejected_reason',
                                  'cancelled_at','updated_at','version']) IS DISTINCT FROM
             (to_jsonb(OLD) - ARRAY['status','confirmed_by','confirmed_at','rejected_reason',
                                  'cancelled_at','updated_at','version'])
          THEN RAISE EXCEPTION 'payment recording facts are immutable'; END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER finance_protection BEFORE UPDATE OR DELETE ON payments "
        "FOR EACH ROW EXECUTE FUNCTION protect_finance_payment()"
    )
    op.execute("""
        CREATE FUNCTION protect_finance_adjustment() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'adjustments cannot be deleted'; END IF;
          IF OLD.status <> 'PENDING_APPROVAL' THEN RAISE EXCEPTION 'final adjustments are immutable'; END IF;
          IF (to_jsonb(NEW) - ARRAY['status','approved_by','approved_at','self_approved',
                                  'rejected_reason','updated_at','version']) IS DISTINCT FROM
             (to_jsonb(OLD) - ARRAY['status','approved_by','approved_at','self_approved',
                                  'rejected_reason','updated_at','version'])
          THEN RAISE EXCEPTION 'adjustment recording facts are immutable'; END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER finance_protection BEFORE UPDATE OR DELETE ON adjustments "
        "FOR EACH ROW EXECUTE FUNCTION protect_finance_adjustment()"
    )
