export const resources = {
  en: {
    translation: {
      brand: { name: 'TezFarmo', tagline: 'The clear way to trade' },
      common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', retry: 'Retry', signOut: 'Sign out', support: 'Support' },
      auth: {
        signIn: 'Sign in', createAccount: 'Create account', welcomeBack: 'Welcome back', join: 'Join TezFarmo', phone: 'Phone number', password: 'Password', fullName: 'Full name', company: 'Company', store: 'Store', continue: 'Continue', verifyPhone: 'Verify phone', creating: 'Creating account...', signingIn: 'Signing in...', google: 'Continue with Google', registerLink: 'Create one', loginLink: 'Sign in', accountReady: 'Your account is ready', code: 'Verification code', resend: 'Resend code', changePhone: 'Use a different number', passwordHint: 'At least 8 characters, with letters and numbers.', roleQuestion: 'What best describes your business?', companyDescription: 'Distributor or supplier managing products, stores, pricing, and fulfillment.', storeDescription: 'Retail store sourcing products and placing orders with suppliers.',
      },
      dashboard: { company: 'Company workspace', store: 'Store workspace', overview: 'Overview', orders: 'Orders', products: 'Products', partners: 'Partners', warehouse: 'Warehouse', delivery: 'Delivery', finance: 'Finance', team: 'Team', subscription: 'Subscription', catalog: 'Catalog', suppliers: 'Suppliers', debt: 'Debt & statements', notifications: 'Notifications', settings: 'Settings', newOrders: 'New orders', todayDelivery: 'Today\'s delivery', receivables: 'Receivables', activeOrders: 'Active orders', overdue: 'Overdue', connectedSupply: 'Your connected supply network' },
      errors: { invalid_credentials: 'That phone number or password is not correct.', phone_already_registered: 'This phone number is already registered. Try signing in.', otp_invalid: 'The verification code is not correct.', otp_expired: 'This verification code has expired. Request a new one.', rate_limited: 'Too many attempts. Please wait and try again.', rate_limit_exceeded: 'Too many attempts. Please wait and try again.', permission_denied: 'You do not have permission for this action.', network: 'We could not reach TezFarmo. Check your connection and try again.', generic: 'Something went wrong. Please try again.' },
    },
  },
  ru: { translation: { brand: { name: 'TezFarmo', tagline: 'Понятная торговля для бизнеса' }, common: { loading: 'Загрузка...', signOut: 'Выйти', support: 'Поддержка', retry: 'Повторить' }, auth: { signIn: 'Войти', createAccount: 'Создать аккаунт', welcomeBack: 'С возвращением', join: 'Присоединиться к TezFarmo', phone: 'Номер телефона', password: 'Пароль', fullName: 'Полное имя', company: 'Компания', store: 'Магазин', continue: 'Продолжить', verifyPhone: 'Подтвердить телефон', creating: 'Создаём аккаунт...', signingIn: 'Входим...', google: 'Продолжить с Google', registerLink: 'Создать аккаунт', loginLink: 'Войти', accountReady: 'Аккаунт готов', code: 'Код подтверждения', resend: 'Отправить код снова', changePhone: 'Изменить номер', passwordHint: 'Минимум 8 символов, буквы и цифры.', roleQuestion: 'Что лучше описывает ваш бизнес?', companyDescription: 'Дистрибьютор или поставщик: товары, магазины, цены и поставки.', storeDescription: 'Розничный магазин: поиск поставщиков и заказы.' }, dashboard: { company: 'Рабочее пространство компании', store: 'Рабочее пространство магазина', overview: 'Обзор', orders: 'Заказы', products: 'Товары', partners: 'Партнёры', warehouse: 'Склад', delivery: 'Доставка', finance: 'Финансы', team: 'Команда', subscription: 'Подписка', catalog: 'Каталог', suppliers: 'Поставщики', debt: 'Долги и выписки', notifications: 'Уведомления', settings: 'Настройки', newOrders: 'Новые заказы', todayDelivery: 'Доставка сегодня', receivables: 'Дебиторка', activeOrders: 'Активные заказы', overdue: 'Просрочено', connectedSupply: 'Ваша сеть поставок' }, errors: { invalid_credentials: 'Неверный номер телефона или пароль.', generic: 'Что-то пошло не так. Попробуйте ещё раз.' } } },
  tg: { translation: { brand: { name: 'TezFarmo', tagline: 'Тиҷорати равшан барои бизнес' }, common: { loading: 'Бор шуда истодааст...', signOut: 'Баромадан', support: 'Дастгирӣ', retry: 'Такрор кардан' }, auth: { signIn: 'Ворид шудан', createAccount: 'Ҳисоб сохтан', welcomeBack: 'Хуш омадед', join: 'Ба TezFarmo ҳамроҳ шавед', phone: 'Рақами телефон', password: 'Парол', fullName: 'Ному насаб', company: 'Фирма', store: 'Мағоза', continue: 'Идома', verifyPhone: 'Телефонро тасдиқ кунед', creating: 'Ҳисоб сохта мешавад...', signingIn: 'Ворид шуда истодааст...', google: 'Бо Google идома диҳед', registerLink: 'Ҳисоб созед', loginLink: 'Ворид шавед', accountReady: 'Ҳисоби шумо омода аст', code: 'Рамзи тасдиқ', resend: 'Рамзро аз нав фиристед', changePhone: 'Рақами дигар', passwordHint: 'Ҳадди ақал 8 аломат, ҳарф ва рақам.', roleQuestion: 'Кадом тавсиф ба бизнеси шумо мувофиқ аст?', companyDescription: 'Тақсимкунанда ё таъминкунанда: мол, мағоза, нарх ва расониш.', storeDescription: 'Мағозаи чакана: таъминкунанда ҷӯед ва фармоиш диҳед.' }, dashboard: { company: 'Муҳити кории фирма', store: 'Муҳити кории мағоза', overview: 'Шарҳи умумӣ', orders: 'Заявкаҳо', products: 'Молҳо', partners: 'Шарикон', warehouse: 'Анбор', delivery: 'Расониш', finance: 'Молия', team: 'Даста', subscription: 'Обуна', catalog: 'Каталог', suppliers: 'Таъминкунандагон', debt: 'Қарз ва ҳисобот', notifications: 'Огоҳиномаҳо', settings: 'Танзимот', newOrders: 'Заявкаҳои нав', todayDelivery: 'Расониши имрӯз', receivables: 'Қарздории мизоҷон', activeOrders: 'Заявкаҳои фаъол', overdue: 'Муҳлат гузашта', connectedSupply: 'Шабакаи таъминоти шумо' }, errors: { invalid_credentials: 'Рақами телефон ё парол нодуруст аст.', generic: 'Мушкил пайдо шуд. Аз нав кӯшиш кунед.' } } },
} as const;

export type SupportedLanguage = keyof typeof resources;
